version: "3"

services:
  planka:
    image: ghcr.io/plankanban/planka:2.0.0-rc.3
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - BASE_URL=https://planka-production-f920.up.railway.app:8080
      - DATABASE_URL=postgresql://postgres:yUJQlINNspHPaqOjRQTMSmuuefOAzVmV@turntable.proxy.rlwy.net:45631/railway
      - SECRET_KEY=notsecretkey
      # Можно добавить логин/пароль админа:
      - DEFAULT_ADMIN_EMAIL=admin@admin.com
      - DEFAULT_ADMIN_PASSWORD=admin
      - DEFAULT_ADMIN_NAME=Admin Admin
      - DEFAULT_ADMIN_USERNAME=admin
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments

volumes:
  favicons:
  user-avatars:
  background-images:
  attachments:
